services:
  sentient_docs:
    container_name: sentient_docs
    build:
      context: .
      dockerfile: Dockerfile
    image: sentient/docs:latest
    restart: unless-stopped
    ports:
      - "8080:80"
