version: '3.1'
services:
  sentient_website:
    container_name: sentient_website
    restart: always
    image: "sentient/website"
    environment:
      PAGES_REPO_NWO: "sentient/sentient.github.io"
    ports:
      - "4000:4000"
    volumes:
      - .:/website