services:
  sentient_website:
    container_name: sentient_website
    restart: always
    image: "thingsboard/website"
    environment:
      PAGES_REPO_NWO: "QuakeString/sentient_docs"
      JEKYLL_ENV: "production"
    ports:
      - "4000:4000"
    volumes:
      - .:/website
