- title: Professional Edition
  fulltitle: SENTIENT Professional Edition
  description: SENTIENT Documentation
  tag: pe
  icon: /images/sentient-p-icon.svg
  path: /docs/pe/
  guides: /docs/pe/guides/
  getStarted: /docs/pe/getting-started-guides/helloworld/
  docsPrefix: /docs/pe/
- title: Cloud
  fulltitle: SENTIENT Cloud
  description: SENTIENT Documentation
  tag: paas
  icon: /images/sentient-c-icon.svg
  path: /docs/paas/
  guides: /docs/paas/guides/
  getStarted: /docs/paas/getting-started-guides/helloworld/
  docsPrefix: /docs/paas/
- title: SENTIENT Edge
  fulltitle: SENTIENT Edge
  description: SENTIENT Edge Documentation
  tag: edge
  icon: /images/sentient-gw-icon.svg
  path: /docs/edge/
  docsPrefix: /docs/edge/
- title: PE SENTIENT Edge
  fulltitle: SENTIENT PE Edge
  description: SENTIENT PE Edge Documentation
  tag: edge-pe
  icon: /images/sentient-gw-icon.svg
  path: /docs/pe/edge/
  docsPrefix: /docs/pe/edge/
- title: SENTIENT Gateway
  fulltitle: SENTIENT Gateway
  description: SENTIENT Documentation
  tag: gw
  icon: /images/gateway-icon.svg
  path: /docs/iot-gateway/
  docsPrefix: /docs/iot-gateway/
  getStarted: /docs/iot-gateway/getting-started/
- title: License Server
  fulltitle: SENTIENT License Server
  description: SENTIENT Documentation
  tag: license
  icon: /images/license-icon.svg
  path: /products/license-server/
- title: SENTIENT ANALYTICS
  fulltitle: SENTIENT ANALYTICS
  description: SENTIENT ANALYTICS Documentation
  tag: sentient-analytics
  icon: /images/sentient-analytics-icon.svg
  path: /docs/sentient-analytics/
  docsPrefix: /docs/sentient-analytics/
  getStarted: /docs/sentient-analytics/getting-started/
- title: Mobile Application
  fulltitle: SENTIENT Mobile Application
  description: Mobile Application Documentation
  tag: mobile
  icon: /images/sentient-mobile-icon.svg
  path: /docs/mobile/
  docsPrefix: /docs/mobile/
  getStarted: /docs/mobile/getting-started/
- title: PE Mobile Application
  fulltitle: SENTIENT PE Mobile Application
  description: PE Mobile Application Documentation
  tag: mobile-pe
  icon: /images/sentient-pe-mobile-icon.svg
  path: /docs/pe/mobile/
  docsPrefix: /docs/pe/mobile/
  getStarted: /docs/pe/mobile/getting-started/
- title: ST-RMQTT
  fulltitle: ST-RMQTT
  description: ST-RMQTT Documentation
  tag: mqtt-broker
  icon: /images/st-rmqtt-icon.svg
  path: /docs/mqtt-broker/
  docsPrefix: /docs/mqtt-broker/
  getStarted: /docs/mqtt-broker/getting-started/
- title: PE ST-RMQTT
  fulltitle: PE ST-RMQTT
  description: PE ST-RMQTT Documentation
  tag: mqtt-broker-pe
  icon: /images/st-rmqtt-icon.svg
  path: /docs/pe/mqtt-broker/
  docsPrefix: /docs/pe/mqtt-broker/
